#pragma once

typedef struct Modules {
  char* mod_name;  /* How the actual loaded kmod file name is seen in `lsmod` */
  char* conf_name; /* CONF_MODULE_NAME=y as appears in Linux kernel's .config */
} Module;

Module modules[] = {
  { "ablk_helper", "CRYPTO_ABLK_HELPER" },
  { "acpi_cpufreq", "X86_ACPI_CPUFREQ" },
  { "ahci", "SATA_AHCI" },
  { "amd_freq_sensitivity", "X86_AMD_FREQ_SENSITIVITY" },
  { "autofs4", "AUTOFS4_FS" },
  { "btrfs", "BTRFS_FS" },
  { "button", "ACPI_BUTTON" },
  { "cfg80211", "CFG80211" },
  { "crc16", "CRC16" },
  { "crc32c_intel", "CRYPTO_CRC32_INTEL" },
  { "crc32_pclmul", "CRYPTO_CRC32_PCLMUL" },
  { "cryptd", "CRYPTO_CRYPTD" },
  { "dca", "DCA" },
  { "ecb", "CRYPTO_ECB" },
  { "ehci_hcd", "USB_EHCI_HCD" },
  { "ehci_pci", "USB_EHCI_PCI" },
  { "evdev", "INPUT_EVDEV" },
  { "fam15h_power", "SENSORS_FAM15H_POWER" },
  { "fat", "FAT_FS" },
  { "fscache", "FSCACHE" },
  { "gf128mul", "CRYPTO_GF128MUL" },
  { "glue_helper", "CRYPTO_GLUE_HELPER_X86" },
  { "hid_generic", "HID_GENERIC" },
  { "hid_roccat", "HID_ROCCAT" },
  { "hid_roccat_common", "HID_ROCCAT" },
  { "hid_roccat_isku", "HID_ROCCAT" },
  { "i2c_piix4", "I2C_PIIX4" },
  { "igb", "IGB" },
  { "iwlwifi", "IWLWIFI" },
  { "joydev", "INPUT_JOYDEV" },
  { "k10temp", "SENSORS_K10TEMP" },
  { "kvm", "KVM" },
  { "kvm_amd", "KVM_AMD" },
  { "lrw", "CRYPTO_LRW" },
  { "mmc_block", "MMC_BLOCK" },
  { "mmc_core", "MMC" },
  { "nls_cp437", "NLS_CODEPAGE_437" },
  { "parport", "PARPORT" },
  { "parport_pc", "PARPORT_PC" },
  { "ppdev", "PPDEV" },
  { "raid6_pq", "RAID6_PQ" },
  { "rfkill", "RFKILL" },
  { "sdhci", "MMC_SDHCI" },
  { "sdhci_pci", "MMC_SDHCI_PCI" },
  { "snd_hda_codec_realtek", "SND_HDA_CODEC_REALTEK" },
  { "snd_hda_intel", "SND_HDA_INTEL" },
  { "snd_hwdep", "SND_HWDEP" },
  { "snd_pcm", "SND_PCM" },
  { "snd_rawmidi", "SND_RAWMIDI" },
  { "snd_timer", "SND_TIMER" },
  { "snd_usb_audio", "SND_USB_AUDIO" },
  { "usb_storage", "USB_STORAGE" },
  { "vfat", "VFAT_FS" },
  { "xor", "XOR_BLOCKS" },
};
